spring:
  datasource:
    url: jdbc:h2:mem:libdbjpa;IGNORECASE=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  messages:
    basename: messages
    encoding: UTF-8

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
