insert into authors (authorName) values ( 'Джон Рональд Руэл Толкин' );
insert into authors (authorName) values ( 'Роджер Желязны' );
insert into authors (authorName) values ( 'Теодор Драйзер' );
insert into authors (authorName) values ( 'Дэн Симмонс' );
insert into authors (authorName) values ( 'Джеральд Даррелл' );
insert into authors (authorName) values ( 'Федор Достоевский' );
insert into authors (authorName) values ( 'Агата Кристи' );
insert into authors (authorName) values ( 'Артур Конан Дойл' );
insert into authors (authorName) values ( 'Александр Дюма' );
insert into authors (authorName) values ( 'Анджей Сапковский' );
insert into authors (authorName) values ( 'Данте Алигьери' );

insert into genres (genreName) values ( 'Фантастика и фэнтези' );
insert into genres (genreName) values ( 'Детектив' );
insert into GENRES (GENRENAME) values ( 'Мемуары' );
insert into GENRES (GENRENAME) values ( 'Роман' );
insert into GENRES (GENRENAME) values ( 'Поэма' );


INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Властелин колец', 1, 1);
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Сильмариллион', 1, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Этюд в багровых тонах', 8, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Знак четырех', 8, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Собака Баскервилей', 8, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Долина ужасов', 8, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Убийство в Восточном экспрессе', 7, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Кража в миллион долларов', 7, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Корнуолльская тайна', 7, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Немезида', 7, 2 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Птицы, звери и родственники', 5, 3 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Под пологом пьяного леса', 5, 3 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Финансист', 3, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Титан', 3, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Стоик', 3, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Братья Карамазовы', 6, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Идиот', 6, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Бесы', 6, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Граф Монте-Кристо', 9, 4 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Гиперион', 4, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Падение Гипериона', 4, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Эндемион', 4, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Восход Эндемиона', 4, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Последнее желание', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Меч Предназначения', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Час Презрения', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Крещение огнем', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Башня Ласточки', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Владычица Озера', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Сезон гроз', 10, 1 );
INSERT INTO BOOKS (BOOKNAME, AUTHORID, GENREID) VALUES ( 'Божественная комедия', 11, 5 );